### PR TITLE
Add support to use a remote Ollama instance.

### PR DESCRIPTION
**Pull request by pjamar**
Add support for `llm-ollama` to connect to a remote instance.

This uses the same environment variable that can be used with the standard `ollama` binary, `OLLAMA_HOST`

### CODE REVIEW

**Comment by taketwo** [comment]
In `ollama-python`, if the `host` argument is not provided to the constructor of `Client`, the value will be read from `OLLAMA_HOST` environment variable: https://github.com/ollama/ollama-python/blob/70dd0b7e639f5b6b39e15963521f1d4c6810464b/ollama/_client.py#L96. Therefore, it should not be necessary to explicitly forward it from this plugin. Did you try setting `OLLAMA_HOST` variable with the non-patched version of the plugin? Did it not work?

**Comment by pjamar** [comment]
Hmm.. I think I tested that using Simon's `llm`, but it didn't seem to work. I'll double check.

Thanks Sergey!

**Comment by pjamar** [comment]
You were right, this works out of the box. Maybe it is worth updating the documentation that we can also connect to remote servers, just by setting the environment variable :)

**Comment by taketwo** [comment]
Thanks for confirming! In fact, there is already a section in the README about non-default host addresses: https://github.com/taketwo/llm-ollama?tab=readme-ov-file#ollama-server-address. I think it's the usage of the word "local" in the repo description and introductory sentence that gives the impression that remote servers are not supported. I'll improve that.

**Comment by pjamar** [comment]
Thanks Sergey!  Yes, that `local` mention at the beginning was what mislead me, but I should have dove deeper in the docs...

**Pull request closed without merging**
