### PR TITLE
Added support for vision models in Ollama

### PR DESCRIPTION
**Pull request by sukhbinder**
Support for attachments, allowing multi-modal models to accept images

Vision models can be called using '-a`

usage example:

```bash

llm -m llava "Describe this image" -a ~/latest.png

```

### CODE REVIEW

**Comment by sukhbinder** [comment]
@taketwo Added vision support using the latest [llm v0.17.](https://github.com/simonw/llm/releases/tag/0.17) Please review and approve

**Comment by sukhbinder** [comment]
>  Could you suggest how I can have a chat with an attachment? `llm chat` does not seem to have a corresponding option.

I think Simon hasn't added the attachment to 'llm chat', so this is not possible as of now.

```bash
llm chat -m llava -a path/to/image
```

But since I have added support as part of the conversation, so a continued conversation is possible like this:

```bash
llm -m llava "Describe this image" -a path/to/image
```

and subsequently call

```bash
llm -c "Count no of people in the image"
```

hope this makes sense.

**Comment by sukhbinder** [comment]
@simonw Is there a plan to add -a/ --attachment option to `llm chat`

**Comment by taketwo** [comment]
Got it, thanks for the explanation, I was able to verify this locally. I've updated your commit to remove formatting changes and avoid repetition in `if/else` blocks. The vision feature is in `master` and part of tagged `0.6.0` release. Thanks again!

**Pull request closed without merging**
