### PR TITLE
Fixes a bug when using llm chat is used with Ollama Model.

### PR DESCRIPTION
**Pull request by sukhbinder**
The error:

388882579-b4218288-0b97-43f6-ae16-a14c6260775f

After the fix, this works.

388882591-93a7a870-9899-456d-9e20-b69185b032ff

### CODE REVIEW

**Comment by taketwo** [comment]
Do you have an up-to-date version of `ollama` Python package installed?

**Comment by sukhbinder** [comment]
> Do you have an up-to-date version of `ollama` Python package installed?

Let me check.

**Comment by sukhbinder** [comment]
No this is an issue with the llm-plugin.

with this commit. 678a50f11055e1ae8007134ef0c038df476f553e   I get this error
Screenshot 2024-11-22 at 17 17 59


Versions:
Screenshot 2024-11-22 at 17 19 52

With the fix 0.8.0
Screenshot 2024-11-22 at 17 21 47

**Comment by sukhbinder** [comment]
Can you please check from your end.

This happens when we use 

```bash
llm chat -m <some-ollama-model>

```

and do a muti turn.

**Comment by taketwo** [comment]
Hm, so everything works fine with `ollama==0.3.3`. However, after I updated to the newest version (0.4.0)[https://github.com/ollama/ollama-python/releases/tag/v0.4.0] that was released today, I started to get errors:
* no "name" attribute in model objects
* no "model_info" attribute in in show response objects
I've made corresponding changes to use new names of these renamed attributes and then I was able to chat with Ollama models. This is strange:
* Why do I not get the "attachment" error?
* Why don't you get same attribute errors as I do?

**Comment by taketwo** [comment]
Note that response objects should always have "attachments" attribute: https://github.com/simonw/llm/blob/335b3e635aa1439edafb13b0c2a225ce5840cc98/llm/models.py#L214

**Comment by sukhbinder** [comment]
> Hm, so everything works fine with `ollama==0.3.3`. However, after I updated to the newest version (0.4.0)[https://github.com/ollama/ollama-python/releases/tag/v0.4.0] that was released today, I started to get errors:
> 
> * no "name" attribute in model objects
> * no "model_info" attribute in in show response objects
> 
> I've made corresponding changes to use new names of these renamed attributes and then I was able to chat with Ollama models. This is strange:
> 
> * Why do I not get the "attachment" error?
> * Why don't you get same attribute errors as I do?

Strange. 

I did get the attribute errors, in the previous update but then I started with a clean state on new venv with Python 3.9.12. What version of python are you testing this on?

**Comment by sukhbinder** [comment]
And  ollama version is 0.4.3 while Ollama python version is ollama  0.4.0

**Comment by taketwo** [comment]
I'm testing on Python v3.12.3. I've pushed a bunch of updates that fix everything for me locally. Would you mind pulling latest `master` and creating a new venv from scratch?

**Comment by sukhbinder** [comment]
Yes I will check in a bit. I think it will work. With an isolated env using uv I am getting the behaviour you are getting. This pr might not be needed. With ollama==0.3.3 and llm-ollama=0.7.0 it’s working like yours. 

Only ollama==0.4.0 fixes are needed

**Comment by sukhbinder** [comment]
I can confirm it's working. 

Screenshot 2024-11-22 at 22 06 25

## versions
Screenshot 2024-11-22 at 22 07 31

**Comment by taketwo** [comment]
Thanks for confirming; I've tagged a new release: https://github.com/taketwo/llm-ollama/releases/tag/0.7.1.

**Pull request closed without merging**
